# Generated by Django 6.0.1 on 2026-02-25 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0005_subscription_model'),
        ('notification', '0001_official_notice_model'),
        ('product', '0005_move_icon_to_solution'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('log_type', models.CharField(choices=[('official', '공문'), ('subscription', '구독 자동발송')], max_length=20, verbose_name='발송 유형')),
                ('channel', models.CharField(choices=[('email', 'Gmail'), ('slack', 'Slack')], max_length=10, verbose_name='채널')),
                ('recipient', models.CharField(max_length=300, verbose_name='수신자')),
                ('subject', models.CharField(blank=True, max_length=300, verbose_name='제목')),
                ('status', models.CharField(choices=[('success', '성공'), ('failed', '실패'), ('pending', '대기')], default='pending', max_length=10, verbose_name='상태')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='발송일시')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_logs', to='customer.customer', verbose_name='고객사')),
                ('official_notice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_logs', to='notification.officialnotice', verbose_name='공문')),
                ('solution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_logs', to='product.solution', verbose_name='솔루션')),
            ],
            options={
                'verbose_name': '발송 로그',
                'verbose_name_plural': '발송 로그 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
