# Generated by Django 6.0.2 on 2026-03-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_dispatch_log_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchlog',
            name='recipient',
            field=models.TextField(verbose_name='수신자'),
        ),
    ]
