# Generated by Django 6.0.2 on 2026-06-04 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_recipient_to_textfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='액션 코드')),
                ('target', models.CharField(max_length=300, verbose_name='대상')),
                ('detail', models.JSONField(blank=True, null=True, verbose_name='상세 정보')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='일시')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to=settings.AUTH_USER_MODEL, verbose_name='수행자')),
            ],
            options={
                'verbose_name': '액션 로그',
                'verbose_name_plural': '액션 로그 목록',
                'ordering': ['-timestamp'],
            },
        ),
    ]
