# Generated by Django 6.0.1 on 2026-01-15 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatchNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('version', models.CharField(max_length=30, verbose_name='버전')),
                ('release_date', models.DateField(verbose_name='배포일')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patch_notes', to='product.product', verbose_name='제품')),
            ],
            options={
                'verbose_name': '패치노트',
                'verbose_name_plural': '패치노트 목록',
                'ordering': ['-release_date'],
                'unique_together': {('product', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Improvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('content', models.TextField(verbose_name='내용')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='patchnote.improvement', verbose_name='상위 항목')),
                ('patch_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvements', to='patchnote.patchnote', verbose_name='기능 개선')),
            ],
            options={
                'verbose_name': '기능 개선',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('content', models.TextField(verbose_name='내용')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='patchnote.feature', verbose_name='상위 항목')),
                ('patch_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='patchnote.patchnote', verbose_name='기능 추가')),
            ],
            options={
                'verbose_name': '기능 추가',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BugFix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('content', models.TextField(verbose_name='내용')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='patchnote.bugfix', verbose_name='상위 항목')),
                ('patch_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugfixes', to='patchnote.patchnote', verbose_name='버그 수정')),
            ],
            options={
                'verbose_name': '버그 수정',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('content', models.TextField(verbose_name='내용')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='patchnote.remark', verbose_name='상위 항목')),
                ('patch_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='patchnote.patchnote', verbose_name='특이사항')),
            ],
            options={
                'verbose_name': '특이사항',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
