# Generated by Django 6.0.1 on 2026-01-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patchnote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugfix',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='내용(영문)'),
        ),
        migrations.AddField(
            model_name='feature',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='내용(영문)'),
        ),
        migrations.AddField(
            model_name='improvement',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='내용(영문)'),
        ),
        migrations.AddField(
            model_name='remark',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='내용(영문)'),
        ),
    ]
