# Generated by Django 6.0.2 on 2026-03-30 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patchnote', '0007_patchnotefile_nextcloud_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('content', models.TextField(verbose_name='내용')),
                ('content_en', models.TextField(blank=True, null=True, verbose_name='내용(영문)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='patchnote.internal', verbose_name='상위 항목')),
                ('patch_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internals', to='patchnote.patchnote', verbose_name='내부 공유')),
            ],
            options={
                'verbose_name': '내부 공유',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
