# Generated by Django 6.0.2 on 2026-05-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patchnote', '0008_add_internal_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='patchnote',
            name='external_send_error',
            field=models.TextField(blank=True, verbose_name='외부 발송 오류'),
        ),
        migrations.AddField(
            model_name='patchnote',
            name='external_send_scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='외부 발송 예약 시각'),
        ),
        migrations.AddField(
            model_name='patchnote',
            name='external_send_status',
            field=models.CharField(choices=[('none', '미발행'), ('pending', '발송 대기'), ('sent', '발송 완료'), ('cancelled', '발송 취소'), ('failed', '발송 실패')], default='none', max_length=15, verbose_name='외부 발송 상태'),
        ),
        migrations.AddField(
            model_name='patchnote',
            name='external_send_task_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='외부 발송 작업 ID'),
        ),
    ]
