# Generated by Django 6.0.2 on 2026-06-04 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patchnote', '0010_patchnote_notion_pushed_at'),
        ('product', '0008_add_utility_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patchnote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='patchnote',
            name='utility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patch_notes', to='product.utility', verbose_name='유틸리티'),
        ),
        migrations.AlterField(
            model_name='patchnote',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patch_notes', to='product.product', verbose_name='제품'),
        ),
        migrations.AddConstraint(
            model_name='patchnote',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('product', 'version'), name='patchnote_product_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='patchnote',
            constraint=models.UniqueConstraint(condition=models.Q(('utility__isnull', False)), fields=('utility', 'version'), name='patchnote_utility_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='patchnote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', False), ('utility__isnull', True)), models.Q(('product__isnull', True), ('utility__isnull', False)), _connector='OR'), name='patchnote_product_xor_utility'),
        ),
    ]
