# Generated by Django 6.0.2 on 2026-06-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patchnote', '0011_add_utility_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='patchnote',
            name='email_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='이메일 제목 (선택)'),
        ),
    ]
