# Generated by Django 6.0.2 on 2026-06-22 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patchnote', '0012_add_email_title_to_patchnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patchnote',
            name='email_title',
        ),
    ]
