# Generated by Django 6.0.2 on 2026-07-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patchnote', '0013_remove_email_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='patchnote',
            name='is_custom',
            field=models.BooleanField(default=False, verbose_name='커스텀 버전 (외부 미배포)'),
        ),
    ]
