# Generated by Django 6.0.1 on 2026-02-25 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0005_subscription_model'),
        ('product', '0005_move_icon_to_solution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('channel', models.CharField(choices=[('email', 'Gmail'), ('slack', 'Slack')], max_length=10, verbose_name='채널')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('frequency', models.CharField(choices=[('immediate', '즉시'), ('daily', '매일'), ('weekly', '매주')], default='immediate', max_length=20, verbose_name='전달 주기')),
                ('max_items', models.PositiveIntegerField(default=5, verbose_name='최대 건수')),
                ('slack_channel', models.CharField(blank=True, help_text='Slack 채널명 (예: #patch-notes)', max_length=200, null=True, verbose_name='Slack 채널')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='customer.customer', verbose_name='고객사')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='product.solution', verbose_name='솔루션')),
            ],
            options={
                'verbose_name': '구독',
                'verbose_name_plural': '구독 목록',
                'ordering': ['customer__name', 'solution__name', 'channel'],
                'unique_together': {('customer', 'solution', 'channel')},
            },
        ),
    ]
