# Generated by Django 6.0.1 on 2026-02-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0001_subscription_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='frequency',
            field=models.CharField(choices=[('weekly', '매주'), ('quarterly', '분기')], default='weekly', max_length=20, verbose_name='전달 주기'),
        ),
    ]
