# Generated by Django 6.0.2 on 2026-03-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0005_add_immediate_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='slack_channel',
            field=models.CharField(blank=True, help_text='Slack 채널 ID', max_length=200, null=True, verbose_name='Slack 채널'),
        ),
    ]
