# Generated by Django 6.0.2 on 2026-06-12 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_add_on_premise'),
        ('subscriber', '0008_customer_subscription_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='담당자명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_emails', to='customer.customer', verbose_name='고객사')),
            ],
            options={
                'verbose_name': '구독 이메일',
                'verbose_name_plural': '구독 이메일 목록',
                'unique_together': {('customer', 'email')},
            },
        ),
    ]
