# Generated by Django 6.0.2 on 2026-06-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0011_utility_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilitysubscription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
