# Generated by Django 6.0.2 on 2026-06-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0012_alter_utilitysubscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitysubscription',
            name='slack_channel',
            field=models.CharField(blank=True, help_text='Slack 채널 ID', max_length=200, null=True, verbose_name='Slack 채널'),
        ),
    ]
