# Generated by Django 6.0.2 on 2026-06-16 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0013_utilitysubscription_slack_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='max_items',
        ),
    ]
