# Generated by Django 6.0.2 on 2026-06-26 02:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0014_remove_subscription_max_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionemail',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='수신 활성화'),
        ),
        migrations.AddField(
            model_name='subscriptionemail',
            name='unsubscribe_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='수신 거부 토큰'),
        ),
    ]
