# Generated by Django 6.0.2 on 2026-05-07 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('category', models.CharField(choices=[('bug', '버그 / 오류'), ('ux', '사용성 개선'), ('feature', '신규 기능 요청'), ('question', '질문 / 사용 문의'), ('other', '기타')], default='ux', max_length=20, verbose_name='분류')),
                ('status', models.CharField(choices=[('open', '접수'), ('reviewing', '검토 중'), ('planned', '반영 예정'), ('in_progress', '진행 중'), ('done', '반영 완료'), ('wont_do', '미반영'), ('duplicate', '중복')], default='open', max_length=20, verbose_name='상태')),
                ('priority', models.CharField(choices=[('low', '낮음'), ('medium', '보통'), ('high', '높음')], default='medium', max_length=10, verbose_name='우선순위')),
                ('page_url', models.CharField(blank=True, max_length=500, verbose_name='발생 화면 URL')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='feedback/%Y/%m/', verbose_name='첨부 파일')),
                ('resolution_note', models.TextField(blank=True, verbose_name='처리 메모')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '피드백',
                'verbose_name_plural': '피드백 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('content', models.TextField(verbose_name='댓글')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feedback.feedback')),
            ],
            options={
                'verbose_name': '피드백 댓글',
                'ordering': ['created_at'],
            },
        ),
    ]
