# Generated by Django 6.0.2 on 2026-05-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='author_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='작성자 표시명'),
        ),
        migrations.AddField(
            model_name='feedbackcomment',
            name='author_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='작성자 표시명'),
        ),
    ]
