# Generated by Django 6.0.2 on 2026-03-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_add_guest_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('dev', 'Dev'), ('se', 'SE'), ('guest', 'Guest')], default='guest', max_length=10, verbose_name='역할'),
        ),
    ]
