# Generated by Django 6.0.1 on 2026-01-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('product', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='customers', to='product.product', verbose_name='구독 제품들'),
        ),
    ]
