# Generated by Django 6.0.1 on 2026-02-20 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_products'),
        ('product', '0005_move_icon_to_solution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '고객사', 'verbose_name_plural': '고객사 목록'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='고객사명'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='customers', to='product.product', verbose_name='구독 제품'),
        ),
        migrations.CreateModel(
            name='CustomerEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='담당자명')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='customer.customer', verbose_name='고객사')),
            ],
            options={
                'verbose_name': '고객사 이메일',
                'verbose_name_plural': '고객사 이메일 목록',
                'unique_together': {('customer', 'email')},
            },
        ),
    ]
