# Generated by Django 6.0.1 on 2026-02-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_options_alter_customer_name_and_more'),
        ('product', '0005_move_icon_to_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='products',
        ),
        migrations.AddField(
            model_name='customer',
            name='solutions',
            field=models.ManyToManyField(blank=True, related_name='customers', to='product.solution', verbose_name='구독 솔루션'),
        ),
    ]
