# Generated by Django 6.0.1 on 2026-02-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_solutions_m2m'),
        ('product', '0005_move_icon_to_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='solutions',
            field=models.ManyToManyField(blank=True, related_name='customers', to='product.solution', verbose_name='구매 솔루션'),
        ),
    ]
