# Generated by Django 6.0.2 on 2026-03-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_subscription_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_on_premise',
            field=models.BooleanField(default=False, verbose_name='On-Premise 설치'),
        ),
    ]
