# Generated by Django 6.0.2 on 2026-06-26 04:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_add_on_premise'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeremail',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='수신 활성화'),
        ),
        migrations.AddField(
            model_name='customeremail',
            name='unsubscribe_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='수신 거부 토큰'),
        ),
    ]
