# Generated by Django 6.0.1 on 2026-02-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('subject', models.CharField(max_length=300, verbose_name='제목')),
                ('body', models.TextField(verbose_name='본문')),
                ('send_mode', models.CharField(choices=[('direct', '직접 입력'), ('solution', '솔루션 선택')], max_length=10, verbose_name='발송 방식')),
                ('recipients_json', models.TextField(blank=True, default='[]', verbose_name='수신자 목록(JSON)')),
                ('recipient_count', models.PositiveIntegerField(default=0, verbose_name='수신자 수')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='발송일시')),
            ],
            options={
                'verbose_name': '공문',
                'verbose_name_plural': '공문 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
