# Generated by Django 6.0.2 on 2026-06-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_official_notice_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_logo', models.ImageField(blank=True, null=True, upload_to='notice_logos/', verbose_name='상단 로고')),
                ('upper_logo_width', models.PositiveIntegerField(default=120, verbose_name='상단 로고 너비 (px)')),
                ('lower_logo', models.ImageField(blank=True, null=True, upload_to='notice_logos/', verbose_name='하단 로고')),
                ('lower_logo_width', models.PositiveIntegerField(default=200, verbose_name='하단 로고 너비 (px)')),
                ('header_color', models.CharField(default='#501A9B', max_length=20, verbose_name='헤더 색상')),
                ('footer_text', models.TextField(default='이 메일은 Patch Notify 시스템에서 자동 발송되었습니다.\n문의사항이 있으시면 담당자에게 연락해 주세요.', verbose_name='하단 문구')),
            ],
            options={
                'verbose_name': '공문 템플릿 설정',
                'verbose_name_plural': '공문 템플릿 설정',
            },
        ),
    ]
