# Generated by Django 6.0.2 on 2026-06-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notice_config_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeconfig',
            name='patchnote_title_format',
            field=models.CharField(default='{product} Release 안내', max_length=200, verbose_name='패치노트 이메일 제목 형식'),
        ),
    ]
