# Generated by Django 6.0.1 on 2026-01-15 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('name', models.CharField(max_length=100, verbose_name='솔루션 명')),
            ],
            options={
                'verbose_name': '솔루션',
                'verbose_name_plural': '솔루션 목록',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('platform', models.CharField(choices=[('AOS', 'Android'), ('IOS', 'iOS'), ('SERVER', 'Server'), ('MACOS', 'macOS'), ('WEB', 'Web'), ('FLUTTER', 'Flutter')], default='AOS', max_length=10, verbose_name='플랫폼')),
                ('category', models.CharField(choices=[('LIB', 'Library'), ('PLG', 'Plugin'), ('BND', 'Backend'), ('FND', 'Frontend'), ('MOD', 'Module')], default='LIB', max_length=10, verbose_name='카테고리')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.solution', verbose_name='소속 솔루션')),
            ],
            options={
                'verbose_name': '상세 제품',
                'verbose_name_plural': '상세 제품 목록',
                'unique_together': {('solution', 'platform', 'category')},
            },
        ),
    ]
