# Generated by Django 6.0.1 on 2026-01-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LIB', 'Library'), ('PLG', 'Plugin'), ('BND', 'Backend'), ('FND', 'Frontend'), ('MOD', 'Module')], default='PLG', max_length=10, verbose_name='카테고리'),
        ),
    ]
