# Generated by Django 6.0.1 on 2026-02-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='아이콘'),
        ),
    ]
