# Generated by Django 6.0.1 on 2026-02-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_add_icon_to_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='icon',
        ),
        migrations.AddField(
            model_name='solution',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='아이콘'),
        ),
    ]
