# Generated by Django 6.0.2 on 2026-06-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_add_order_to_solution_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='solution_type',
            field=models.CharField(choices=[('product', 'Product'), ('tool', 'Tool')], default='product', max_length=10, verbose_name='솔루션 유형'),
        ),
    ]
