# Generated by Django 6.0.2 on 2026-06-04 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_add_solution_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('name', models.CharField(max_length=100, verbose_name='유틸리티 명')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('solution', models.ForeignKey(limit_choices_to={'solution_type': 'tool'}, on_delete=django.db.models.deletion.CASCADE, related_name='utilities', to='product.solution', verbose_name='소속 솔루션')),
            ],
            options={
                'verbose_name': '유틸리티',
                'verbose_name_plural': '유틸리티 목록',
                'ordering': ['order', 'name'],
                'unique_together': {('solution', 'name')},
            },
        ),
    ]
