# Generated by Django 6.0.2 on 2026-06-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_add_utility_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utility',
            options={'ordering': ['platform', 'order', 'name'], 'verbose_name': '유틸리티', 'verbose_name_plural': '유틸리티 목록'},
        ),
        migrations.AlterUniqueTogether(
            name='utility',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='utility',
            name='platform',
            field=models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web'), ('common', '공통')], default='common', max_length=10, verbose_name='플랫폼'),
        ),
        migrations.AlterField(
            model_name='utility',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='유틸리티 명'),
        ),
        migrations.RemoveField(
            model_name='utility',
            name='solution',
        ),
    ]
