# Generated by Django 6.0.2 on 2026-06-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_utility_platform_no_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='utility',
            name='has_download',
            field=models.BooleanField(default=False, help_text='체크 시 패치노트에 파일 업로드 UI가 표시됩니다.', verbose_name='다운로드 파일 여부'),
        ),
    ]
