# Generated by Django 6.0.2 on 2026-06-04 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0002_notionpagemapping_sync_tracking'),
        ('product', '0008_add_utility_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='notionpagemapping',
            name='utility',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notion_mapping', to='product.utility', verbose_name='유틸리티'),
        ),
        migrations.AlterField(
            model_name='notionpagemapping',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notion_mapping', to='product.product', verbose_name='제품'),
        ),
    ]
