# Generated by Django 6.0.2 on 2026-05-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='external_send_delay_minutes',
            field=models.PositiveIntegerField(default=30, help_text='발행 후 고객사로 Slack/Gmail 발송까지의 지연 시간 (0이면 즉시 발송)', verbose_name='외부 발송 지연 (분)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='internal_slack_bot_token',
            field=models.CharField(blank=True, help_text='xoxb- 로 시작하는 Bot User OAuth Token', max_length=200, verbose_name='사내 Slack Bot Token'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='internal_slack_channel',
            field=models.CharField(blank=True, help_text='채널 ID 또는 채널명 (예: C0123ABCD 또는 #patch-notify-internal)', max_length=100, verbose_name='사내 Slack 채널'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='internal_slack_enabled',
            field=models.BooleanField(default=False, verbose_name='사내 Slack 알림 활성화'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
