# Generated by Django 6.0.2 on 2026-05-07 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_siteconfig_external_send_delay_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='internal_slack_bot_token',
        ),
    ]
