# Generated by Django 6.0.2 on 2026-05-07 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_is_internal_workspace_remove_bot_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='internal_slack_channel',
        ),
    ]
