# Generated by Django 6.0.2 on 2026-06-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_rename_web_base_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='patchnote_url',
            field=models.CharField(blank=True, help_text='Slack 홈탭에 표시할 전체 패치노트 조회 페이지 URL', max_length=300, verbose_name='패치노트 조회 URL'),
        ),
    ]
