# Generated by Django 6.0.1 on 2026-02-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0001_slack_workspace_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackworkspace',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='slackworkspace',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시'),
        ),
    ]
