# Generated by Django 6.0.2 on 2026-05-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0002_alter_slackworkspace_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackworkspace',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='체크 시 사내 알림 발송에 사용됩니다. 1개만 활성화하세요.', verbose_name='사내 워크스페이스'),
        ),
    ]
